# Generated by Django 4.2.7 on 2026-05-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("inventory", "0003_alter_item_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="inventory.item",
            ),
        ),
        migrations.AlterField(
            model_name="issueitem",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.location"
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="inventory.item",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.location"
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="core.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="inventory.item",
            ),
        ),
        migrations.AlterField(
            model_name="stockledger",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="inventory.location",
            ),
        ),
    ]
