# Generated by Django 4.2.7 on 2026-05-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0002_initial"),
        ("fuel", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuellog",
            name="truck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fuel_logs",
                to="trucks.truck",
            ),
        ),
    ]
