# Generated by Django 4.2.7 on 2026-05-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0002_initial"),
        ("tyres", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tyreassignment",
            name="truck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tyre_assignments",
                to="trucks.truck",
            ),
        ),
        migrations.AlterField(
            model_name="tyreassignment",
            name="tyre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="tyres.tyre",
            ),
        ),
        migrations.AlterField(
            model_name="tyreswap",
            name="from_truck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swaps_from",
                to="trucks.truck",
            ),
        ),
        migrations.AlterField(
            model_name="tyreswap",
            name="to_truck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swaps_to",
                to="trucks.truck",
            ),
        ),
        migrations.AlterField(
            model_name="tyreswap",
            name="tyre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swaps",
                to="tyres.tyre",
            ),
        ),
    ]
