# Generated by Django 4.2.7 on 2026-05-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0002_initial"),
        ("inventory", "0004_alter_issueitem_item_alter_issueitem_location_and_more"),
        ("maintenance", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancelog",
            name="truck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_logs",
                to="trucks.truck",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancepart",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.item"
            ),
        ),
    ]
